"""Project domain: models, registry, and read-only detection wrappers (M3)."""

from adcc.projects.models import (
    RESOURCE_KINDS,
    make_project,
    make_resource,
    make_workspace,
    project_summary,
    validate_project,
    validate_resource,
    validate_workspace,
)
from adcc.projects.registry import (
    DEFAULT_WORKSPACE_ID,
    UNASSIGNED_PROJECT_ID,
    UNASSIGNED_PROJECT_NAME,
    assign_resources_from_apps,
    create_project,
    create_resource,
    delete_project,
    delete_resource,
    ensure_default_workspace,
    ensure_unassigned_project,
    get_project,
    get_resource,
    list_projects,
    list_resources,
    update_project,
    update_resource,
)

__all__ = [
    "DEFAULT_WORKSPACE_ID",
    "RESOURCE_KINDS",
    "UNASSIGNED_PROJECT_ID",
    "UNASSIGNED_PROJECT_NAME",
    "assign_resources_from_apps",
    "create_project",
    "create_resource",
    "delete_project",
    "delete_resource",
    "ensure_default_workspace",
    "ensure_unassigned_project",
    "get_project",
    "get_resource",
    "list_projects",
    "list_resources",
    "make_project",
    "make_resource",
    "make_workspace",
    "project_summary",
    "update_project",
    "update_resource",
    "validate_project",
    "validate_resource",
    "validate_workspace",
]
